#!/bin/sh
# d2cdb executable binary installer
# modified from Matthew Story's generic executable installer
# -p sets the prefix directory
barf()  { echo "${0##*/}: fatal: $*" >&2; exit 100; }
safe()  { "$@" || barf "cannot $*"; }
usage() { echo "${0##*/} [-p prefix] [-s srcdir] [-m mode] [-o owner] [-g group]"; }
owner="$(id -u)"
group="$(id -g)"
prefix=/usr/local
srcdir=src/
mode=555
target="d2cdb"

while true; do
    case "$1" in
        -p) prefix="$2"
            shift 2
            ;;
        -s) srcdir="$2"
            shift 2
            ;;
        -m) mode="$2"
            shift 2
            ;;
        -o) owner="$2"
            shift 2
            ;;
        -g) group="$2"
            shift 2
            ;;
        --) shift
            break
            ;;
        -*) usage
            ;;
         *) break
            ;;
    esac
done
[ -d "$srcdir" ] || barf "directory $srcdir does not exist"
bindir="$prefix/bin"
[ -d "$bindir" ] || barf "directory $bindir does not exist"

find "$srcdir" -depth 1 -type f -name "$target" | xargs -J % \
    install -o "$owner" -g "$group" -m "0${mode}" % "$bindir"
